# fish shell abbreviations sourced for git

NAME "ga"    ; abbr --add ga    "git add"
NAME "gaa"   ; abbr --add gaa   "git add --all"
NAME "gb"    ; abbr --add gb    "git branch"
NAME "gbd"   ; abbr --add gbd   "git branch --delete"
NAME "gc"    ; abbr --add gc    "git checkout"
NAME "gcb"   ; abbr --add gcb   "git checkout -b"
NAME "gcm"   ; abbr --add gcm   "git commit"
NAME "gcmm"  ; abbr --add gcmm  "git commit -m"
NAME "gf"    ; abbr --add gf    "git fetch"
NAME "gp"    ; abbr --add gp    "git push"
NAME "gpo"   ; abbr --add gpo   "git push origin"
NAME "gpom"  ; abbr --add gpom  "git push origin master"
NAME "gpl"   ; abbr --add gpl   "git pull"
NAME "gplo"  ; abbr --add gplo  "git pull origin"
NAME "gplom" ; abbr --add gplom "git pull origin master"
NAME "gs"    ; abbr --add gs    "git status"
NAME "gss"   ; abbr --add gss   "git status -s"
